### ISSUE TITLE
Add basic date functions

### ISSUE THREAD

**Issue by fullpipe** [fullpipe/icu-mf#3]
How it should work https://unicode-org.github.io/icu/userguide/format_parse/datetime/#producing-normal-date-formats-for-a-locale

```yaml
date:
  short:  {when, date, short}
  medium:  {when, date, medium}
  long:  {when, date, long}
  full:  {when, date, full}

time:
  short:  {when, time, short}
  medium:  {when, time, medium}
  long:  {when, time, long}
  full:  {when, time, full}

datetime:
  short:  {when, datetime, short}
  medium:  {when, datetime, medium}
  long:  {when, datetime, long}
  full:  {when, datetime, full}
```

```go
tr.Trans("datetime.medium", mf.Time("when", time.Now()))
tr.Trans("time.long", mf.Time("when", time.Now()))
```
